version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  web:
    build: ./webapp
    ports:
      - "5001:5000"
    depends_on:
      - db
    environment:
      - FLASK_APP=app.py
